[build]
builder = "nixpacks"
buildCommand = "npx prisma generate && npx prisma db push && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
