[build]
builder = "nixpacks"
buildCommand = "npx prisma generate && npm run build"

[deploy]
startCommand = "npx prisma db push && npm start"
healthcheckPath = "/"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
